### ISSUE TITLE
missing credits

### ISSUE THREAD

**Issue by janAkali** [hotshotz79/NX-Game-Icon-Customizer#1]
I think you forgot to give credit to actual creator of sys-tweak module - p-sam and I'd recommend you to change link leading to gbatemp to source: https://github.com/p-sam/switch-sys-tweak for avoiding any misunderstandings.

**Comment by hotshotz79** [comment]
Thank you.... Don't know how I missed the first person I should have thanked >.<
ReadMe now updated, thanks again!
